openapi: "3.0.2"
info:
  title: Roomate BFF API
  version: "1.0"
servers:
  - url: https://arcane-anchorage-82385.herokuapp.com
    description: Servidor de Heroku

tags:
  - name: usuarios
    description: Controlador de Usuarios

paths:
  /usuarios:
    $ref: "pathItems/usuarios/usuarios.yaml"
  /usuarios/buscar:
    $ref: "pathItems/usuarios/usuarios_buscar.yaml"
  /usuarios/{idUsuario}:
    $ref: "pathItems/usuarios/usuarios_idUsuario.yaml"
  /usuarios/{idUsuario}/intereses:
    $ref: "pathItems/usuarios/usuarios_idUsuario_intereses.yaml"
  /usuarios/{idUsuario}/rec_mult:
    $ref: "pathItems/usuarios/usuarios_idUsuario_recMult.yaml"
  /usuarios/{idUsuario}/rec_mult/{idRecMult}:
    $ref: "pathItems/usuarios/usuarios_idUsuario_recMult_idRecMult.yaml"
  /usuarios/{idUsuario}/likes_enviados:
    $ref: "pathItems/usuarios/usuarios_idUsuario_likesEnviados.yaml"
  /usuarios/{idUsuario}/likes_recibidos:
    $ref: "pathItems/usuarios/usuarios_idUsuario_likesRecibidos.yaml"
  /usuarios/{idUsuario}/likes/buscar:
    $ref: "pathItems/usuarios/usuarios_idUsuario_likes_buscar.yaml"
  /usuarios/{idUsuario}/likes:
    $ref: "pathItems/usuarios/usuarios_idUsuario_likes.yaml"
  /usuarios/{idUsuario}/likes/{idUsuarioDestino}:
    $ref: "pathItems/usuarios/usuarios_idUsuario_likes_idUsuarioDestino.yaml"
  /usuarios/{idUsuario}/matches:
    $ref: "pathItems/usuarios/usuarios_idUsuario_matches.yaml"

components:
  schemas:
    # Usuarios
    Usuario:
      $ref: "schemas/usuarios/Usuario.yaml"
    CreacionUsuario:
      $ref: "schemas/usuarios/CreacionUsuario.yaml"
    ActualizacionParcialUsuario:
      $ref: "schemas/usuarios/ActualizacionParcialUsuario.yaml"
    CreacionInteresesUsuario:
      $ref: "schemas/usuarios/CreacionInteresesUsuario.yaml"
    EliminacionInteresesUsuario:
      $ref: "schemas/usuarios/EliminacionInteresesUsuario.yaml"
