openapi: "3.0.2"
info:
  title: Roomate BFF API
  version: "1.0"
servers:
  - url: https://arcane-anchorage-82385.herokuapp.com
    description: Servidor de Heroku

tags:
  - name: usuarios
    description: Controlador de Usuarios

paths:
  /usuarios:
    $ref: "pathitems/usuarios/usuarios.yaml"

components:
  schemas:
    # Usuarios
    Usuario:
      $ref: "schemas/usuarios/Usuario.yaml"
    CreacionUsuario:
      $ref: "schemas/usuarios/CreacionUsuario.yaml"
